import os
from datetime import datetime
from typing import List
from agent.state import Source


def generate_report(query: str, synthesis: str, sources: List[Source]) -> str:
    """Generate a structured Markdown research report."""
    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    num_sources = len(sources)

    sources_section = "\n".join(
        [
            f"{i+1}. [{s['title'] or s['url']}]({s['url']})  \n"
            f"   *Credibility score: {s['credibility_score']:.2f}*"
            for i, s in enumerate(sources)
        ]
    )

    report = f"""# Research Report

**Query:** {query}  
**Generated:** {timestamp}  
**Sources analyzed:** {num_sources}

---

## Executive Summary

{synthesis}

---

## Sources

{sources_section}

---

*Generated by AI Research Agent — powered by LangGraph + Tavily + Claude*
"""

    os.makedirs("outputs", exist_ok=True)
    slug = query[:40].replace(" ", "_").replace("/", "-").replace("?", "").replace(":", "").replace("*", "").replace("|", "")
    filename = f"outputs/report_{slug}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"\n✅ Report saved to: {filename}")

    return report


def export_pdf(report_md: str, output_path: str) -> str:
    """Convert a Markdown report to PDF using ReportLab."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.units import cm
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

        doc = SimpleDocTemplate(output_path, pagesize=A4,
                                leftMargin=2*cm, rightMargin=2*cm,
                                topMargin=2*cm, bottomMargin=2*cm)
        styles = getSampleStyleSheet()
        story = []

        for line in report_md.split("\n"):
            if line.startswith("# "):
                story.append(Paragraph(line[2:], styles["Title"]))
            elif line.startswith("## "):
                story.append(Spacer(1, 12))
                story.append(Paragraph(line[3:], styles["Heading2"]))
            elif line.strip() == "---":
                story.append(Spacer(1, 8))
            elif line.strip():
                story.append(Paragraph(line, styles["Normal"]))
            else:
                story.append(Spacer(1, 6))

        doc.build(story)
        print(f"📄 PDF saved to: {output_path}")
        return output_path

    except ImportError:
        print("⚠️  ReportLab not installed. Run: pip install reportlab")
        return ""